"use strict";

(function exposeScenarios(root) {
  const SCENARIOS = [
    {
      id: "parcel-evening",
      name: "Parcel pickup evening",
      short: "Ordinary pickup desk with mild queueing.",
      lambda: 1.15,
      mu: 0.55,
      servers: 3,
      capacity: 18,
      sourcePopulation: 0,
      patienceMean: 12,
      resourceCapacity: 5,
      resourceMin: 1,
      resourceMax: 2,
      observation: 1440,
      warmup: 120,
      longWait: 10,
      seed: 11111,
    },
    {
      id: "bank-small-lobby",
      name: "Bank branch small lobby",
      short: "Lunch rush with limited waiting room.",
      lambda: 1.05,
      mu: 0.2,
      servers: 4,
      capacity: 10,
      sourcePopulation: 0,
      patienceMean: 35,
      resourceCapacity: 6,
      resourceMin: 1,
      resourceMax: 1,
      observation: 1440,
      warmup: 120,
      longWait: 15,
      seed: 22222,
    },
    {
      id: "clinic-triage",
      name: "Walk-in clinic triage",
      short: "Long service times create impatient waiting.",
      lambda: 0.42,
      mu: 0.12,
      servers: 4,
      capacity: 28,
      sourcePopulation: 0,
      patienceMean: 35,
      resourceCapacity: 5,
      resourceMin: 1,
      resourceMax: 2,
      observation: 1440,
      warmup: 120,
      longWait: 30,
      seed: 33333,
    },
    {
      id: "coffee-mobile",
      name: "Coffee shop mobile pickup",
      short: "Many orders, but only a few shared machines.",
      lambda: 1.8,
      mu: 0.45,
      servers: 5,
      capacity: 24,
      sourcePopulation: 0,
      patienceMean: 7,
      resourceCapacity: 3,
      resourceMin: 1,
      resourceMax: 2,
      observation: 720,
      warmup: 60,
      longWait: 8,
      seed: 44444,
    },
    {
      id: "campus-repair",
      name: "Campus laptop repair",
      short: "Finite campus demand with diagnostic benches.",
      lambda: 0.55,
      mu: 0.22,
      servers: 3,
      capacity: 12,
      sourcePopulation: 45,
      patienceMean: 80,
      resourceCapacity: 4,
      resourceMin: 1,
      resourceMax: 2,
      observation: 3000,
      warmup: 250,
      longWait: 45,
      seed: 55555,
    },
  ];
  const api = { SCENARIOS };
  root.Lab10Scenarios = api;
  if (typeof module !== "undefined") module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : window);
